### ISSUE TITLE
Unable to install on R 4.0.0

### ISSUE THREAD

**Issue by sdmcallister** [MilesMcBain/datapasta#111]
Receiving this message in terminal:
```
Warning in install.packages :
  package ‘datapaste’ is not available (for R version 4.0.0)
```

**Comment by cderv** [comment]
> package ‘datapast**e**’ is not available

I think you just have a typo : it is `datapasta` with an `a` at the end, not `datapaste` . 
This works for me 
```r
install.packages("datapasta")
```

**Comment by sdmcallister** [comment]
oops. thanks. sorry about the noise.
