### ISSUE TITLE
NA values in integers entered as 'NAL' when pasting

### ISSUE THREAD

**Issue by williamlai2** [MilesMcBain/datapasta#114]
For example copying this list from an excel file, then pasting as vector:
```
c(85L, 25L, NA, 50L, 95L, 100L, 40L, 50L)
```
Which produces an error:
> Error: object 'NAL' not found

Otherwise, when pasting as a data frame, the NA values are skipped:
```
data.frame(V1 = c(85L, 25L, 50L, 95L, 100L, 40L, 50L))
```

**Comment by MilesMcBain** [comment]
Thanks for the issue. I've fixed it for vectors.

The data.frame behaviour will remain for now, since it is convenient for the handling of empty rows, which is what this is appearing as.
