### ISSUE TITLE
dpasta error on Date

### ISSUE THREAD

**Issue by mps9506** [MilesMcBain/datapasta#115]
Hi,
Thanks for the wonderful package. I'm running into the following error when using `dpasta()` on a tibble with a `Date` type column. This seems related to #58 . I'm using the current published version 3.1.0 from CRAN.
```r
Error in strrep(" ", char_length - nchar(char_vec)) : 
  invalid 'times' value
```

Starting with `POSIXct` the expected result are returned:

```r
df <- tibble(x = seq(from = Sys.time(),
                     by = "day", 
                     length.out = 10),
             y = rnorm(10))

df %>%
  dpasta()
```

Mutate the column with `as.Date` and the above error is produced:
```r
df %>%
  mutate(x = as.Date(x)) %>%
  datapasta::dpasta()

Error in strrep(" ", char_length - nchar(char_vec)) : 
  invalid 'times' value
```

Finally, the workaround is to mutate to character:

```r
df %>%
  mutate(x = as.Date(x)) %>%
  mutate(x = as.character(x)) %>%
  datapasta::dpasta()
```

**Comment by MilesMcBain** [comment]
Thanks for the reprex! This is fixed now in dev version. Release to CRAN coming in next 2 weeks.
