### ISSUE TITLE
RStudio code error when using add-in

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [MilesMcBain/datapasta#116]
Hi datapasta developers / maintainers! I'm having a problem I've never had before-- when I try to use the `datapasta` Add-in in RStudio to paste as anything (vector, tibble, data.frame), I get a pop up that says "R code execution error" -- when I click "ok" in the notification, I get the following error in the Console:

```
"Error in callFun("insertText", location, text, id) : 
  argument "text" is missing, with no default"
```
 I have gotten that window several times, even after uninstalling and re-installing `datapasta`. Has anyone else gotten this error? I'm wondering if it's a dependency or just an update I need to do.

My sessionInfo() is below. Thank you in advance for your help.

```{r}
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3 
```

**Comment by MattCowgill** [comment]
This is also happening for me! I'm running macOS 11.0, R 4.0.3

**Comment by daleericko** [comment]
Same is happening for me.

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

**Comment by MilesMcBain** [comment]
Thanks for the reports all. I am reasonably confident the root cause of this is a regression in RStudio/rstudioapi that has a fix:

https://github.com/rstudio/rstudioapi/issues/208

You may need to update both `{rstudioapi}` and RStudio itself to get this working again.

**Comment by daleericko** [comment]
Hi Miles - Thank you very much for your prompt reply.
I updated both my RStudio and rstudioapi but still got the same error. I even tried updating to the latest development version of rstudioapi

**Comment by MattCowgill** [comment]
It's working for me now on macOS after updating to the latest RStudio preview release (`1.4.1066`) and updating `rstudioapi`. Thanks Miles.

**Comment by daleericko** [comment]
Thank you @MilesMcBain and @MattCowgill -- With the RStudio preview release all is working for me. Thank you!

**Comment by MargaretSiple-NOAA** [comment]
It works for me too now! I updated `{rstudioapi}` and am using RStudio 1.3.1093.
