### ISSUE TITLE
Error: 'ranges' should be a list of 4-element integer vectors

### ISSUE THREAD

**Issue by daranzolin** [MilesMcBain/datapasta#122]
Apologies for the lack of reprex. I'm trying to datapasta what looks to my eyes like a simple HTML table (from a proprietary source):

<img width="1129" alt="Screen Shot 2021-07-22 at 4 55 22 PM" src="https://user-images.githubusercontent.com/9537384/126723013-17c79882-af21-4716-9206-4ccf69ebf3ee.png">

datapasta errors with: 

```
Error: 'ranges' should be a list of 4-element integer vectors
```

Is there something fishy about the underlying HTML? Not sure how to approach this and datapasta is the ideal solution.

**Comment by daranzolin** [comment]
It was actually dead simple to just paste the values into a text file and `read_tsv`.

**Comment by MilesMcBain** [comment]
This is an error being thrown by the r {rstudioapi}. Do you use VSCode or RStudio? I saw some reports of similar stuff from RStudio users mid last year, this was fixed by updating RStudio.
