### ISSUE TITLE
Dates in vectors using dpasta()

### ISSUE THREAD

**Issue by williamlai2** [MilesMcBain/datapasta#127]
There is an issue with `dpasta()` and dates in a vector format. 

For example, this doesn't produce any output.

```
x <- as.Date("2021-01-01")
datapasta::dpasta(x)
```

Whereas something like `dput(x)` does work.

This could probably be partly solved by something like `else_if(class(input) == "Date)"` in datapasta.R.

**Comment by MilesMcBain** [comment]
This is fixed in 3.1.1 available from R Universe or Github. There's no fix for CRAN in the pipeline at the moment.
