### ISSUE TITLE
Could not find function ".rs.readUiPref" when calling in VS Code

### ISSUE THREAD

**Issue by tarensanders** [MilesMcBain/datapasta#129]
Hi Miles,

Really love the work on this package, and the effort to make RStudio add-ins available in VS Code.

I'm running into problems running datapasta in VS Code. Specifically, if I try to paste a data.frame (or tibble, or anything else) I get the following error:

```r
r$> datapasta:::df_paste()

Error in .rs.readUiPref("num_spaces_for_tab") :
  could not find function ".rs.readUiPref"
```

Per https://github.com/MilesMcBain/datapasta/issues/61#issuecomment-354896053, calling `.rs.readUiPref('num_spaces_for_tab')` direct from the console gives a 'could not find function'. Both datapasta and `.rs.readUiPref("num_spaces_for_tab")` work as expected in Rstudio (`.rs.readUiPref("num_spaces_for_tab")` returns `2`).

Other Rstudio add-ins called from VS Code work as expected (i've tried, styler, reprex, and a couple of others).

I'm using VS Code 1.64.2 on Windows 11, with vscode-R v2.3.8, R 4.1.2, and radian 0.5.12.

Any suggestions?

**Comment by jongjinyun** [comment]
Datapasta 3.1.0 on CRAN was designed only for Rstudio. Try to ‘remotes::install_github(MilesMcBain/datapasta)’. Github version of 'Datapasta' uses 'rstudioapi' package instead of extracting variables directly from Rstudio.

**Comment by tarensanders** [comment]
Yep, that did the trick. Any idea if this is intentional? The README has a section on [other editors](https://github.com/MilesMcBain/datapasta#use-with-other-editors) but it doesn't mention needing the GitHub version.

**Comment by MilesMcBain** [comment]
Thanks @jongjinyun for the tip.

@tarensanders, yes there should probably be something in the README about this.

**Comment by seanthimons** [comment]
I just came across this error with version 3.2.1 on Positron; it doesn't seem to be grabbing (non-existent) RStudio prefs. The GitHub, CRAN, and R-Universe versions all show the same behavior; was the workaround patched out @MilesMcBain ?

**Comment by MilesMcBain** [comment]
Positron did not implement the underlying rstudioapi function, but my understanding is that it is coming in the December release. You can follow: https://github.com/posit-dev/positron/issues/10325

Hopefully not too long a wait.
