### ISSUE TITLE
Data pasted in from Excel as vector contains literal tab characters etc

### ISSUE THREAD

**Issue by francisbarton** [MilesMcBain/datapasta#135]
In RStudio if I copy some data from an Excel sheet and use the datapasta extension to paste as vector, it is not working for me at the moment. (I'm sure it always used to work - this extension has saved me loads of time in the past!)

**Steps to reproduce:**

Create a small table in Excel:

| Item | Location | Notes |
| --- | --- | --- |
| 1 | Here | Hmmm |

Select and copy.

In RStudio, using `Addins > Datapasta > Paste as tribble` works fine:

```r
# paste as tribble
tibble::tribble(
  ~Item, ~Location, ~Notes,
     1L,    "Here", "Hmmm"
  )
```

but when I select `Paste as vector` I get:

```r
# paste as vector
c("Item\tLocation\tNotes", "1\tHere\tHmmm", "䔀")
```

and with `Paste as vector (vertical)` I get:

```r
# paste as vector (vertical)
c("Item\tLocation\tNotes",
  "1\tHere\tHmmm",
  "䔀",
  "椀⥤")
```

The Oriental characters are potentially just a weird artefact of copying from Excel (?) but the vector being pasted raw with the `\t` codes not being interpreted as actual tabs etc is not the behaviour I was expecting.

If just use <kbd>Ctrl</kbd> <kbd>V</kbd> to paste, I get:

```
Item	Location	Notes
1	Here	Hmmm
```
without the stray characters.

(Note that the more I paste, the more extra unwated characters get appended to the paste - it's a bit weird. I end up with things like this:
```r
c("Item\tLocation\tNotes", "1\tHere\tHmmm", "᠀˳䊐\ua7ebȀ耀Item\tLocation\tNotes", "1\tHere\tHmmm", "᠀˳䊏ꟶϱ耀")
```
after a  few attempts to paste.

- RStudio 2022.12.0+353 "Elsbeth Geranium" Release for Windows Electron/19.1.3
- R 4.2.2
- Excel Professional 2016
- datapasta 3.1.1 (R-Universe)

**Comment by MilesMcBain** [comment]
Thanks for raising this issue.

So your desired vector has length 6? I am not sure this has ever worked as you need. The reason is to do with delimeter guessing. As a vector your data is delimited by `\t` and `\n`, and `{datapasta}` will only choose one of these to be the delimeter in the vector case. The data.frame / tribble case allows for each row to be delmited by `\n` along with a separate within-row delimeter.

Not sure what’s going on with the strange characters, I don’t see them on my end, but I only have LibreOffice Calc to hand.

**Comment by francisbarton** [comment]
Thanks Miles - I can't remember what I was expecting from 'paste as vector'! Maybe a named vector of length 3? Anyway - your explanation makes sense, and the paste as tribble option works fine.

No idea about the extraneous characters - I may try to do some digging and provide a more detailed reprex/investigation if i come up against it again.
