### ISSUE TITLE
Pasting from Excel to tribble (locale Polish) decimal point ",", system delimiter ";"

### ISSUE THREAD

**Issue by jacekkotowski** [MilesMcBain/datapasta#26]
Pasting from Excel to tribble (locale Polish: decimal point ",", system delimiter ";" ) turns the numeric column into text: 
tribble(
    ~A,    ~B,  ~C,   ~D,
     3, "7,4",   5,    5,
     5,   "9",   8,    5,
    10,   "9",   3,   10,
     2,   "7",   9,    5,
    10,   "7",   2,    7,
    10,  "10",   2,   10,
     1,   "7",   4,    9
  )
Can the add-in be modified either to accept some settings or read them from the system?
Great plugin! Big thanks for addressing copy paste functinality!

**Comment by MilesMcBain** [comment]
Thanks for raising this. Can you please paste the raw form of that directly from Excel into the issue here?

**Comment by jacekkotowski** [comment]
If I paste it direct from Excel it looks like:
![obraz](https://cloud.githubusercontent.com/assets/11072338/22502094/cca5cf4a-e86b-11e6-9618-cc0c511d5739.png)

If I do it via Notepad++

A	B	C	D
3	7,4	5	5
5	9	8	5
10	9	3	10
2	7	9	5
10	7	2	7
10	10	2	10
1	7	4	9

If I save it to CSV, my system saves

A;B;C;D
3;7,4;5;5
5;9;8;5
10;9;3;10
2;7;9;5
10;7;2;7
10;10;2;10
1;7;4;9

If I want to get the clipboard right int a data.table in R I need to do it with command:
read.table(file="clipboard",header=T, sep = "\t", dec = ",")

I hope it is helpful. Wish you all the best. J

**Comment by MilesMcBain** [comment]
This is great! Thankyou :)

**Comment by MilesMcBain** [comment]
Hi @jacekkotowski, can you please tell me the output of the R function`Sys.getlocale()` on your system?

**Comment by MilesMcBain** [comment]
I think I might be able to use some tools in `readr` to address this issue. The curious thing though is that if I run: `readr::locale("pl")`, I get:

```
> locale("pl")
<locale>
Numbers:  123,456.78
Formats:  %AD / %AT
Timezone: UTC
Encoding: UTF-8
<date_names>
Days:   niedziela (niedz.), poniedziałek (pon.), wtorek
        (wt.), środa (śr.), czwartek (czw.), piątek
        (pt.), sobota (sob.)
Months: stycznia (sty), lutego (lut), marca (mar), kwietnia
        (kwi), maja (maj), czerwca (cze), lipca
        (lip), sierpnia (sie), września (wrz),
        października (paź), listopada (lis), grudnia
        (gru)
AM/PM:  AM/PM
```

With a decimal mark of '.'!

**Comment by MilesMcBain** [comment]
I've added a function that can set the decimal mark: `datapasta::set_decimal_mark` currently on bugfixes branch.
