### ISSUE TITLE
tibble as a dependency

### ISSUE THREAD

**Issue by jonocarroll** [MilesMcBain/datapasta#3]
I know, you dont **actually** depend on it for this code to execute, but for this to be usable, it would be nice to have `tibble` loaded and `tribble()` available. Maybe `Suggests`?

**Comment by MilesMcBain** [comment]
Yeah I was going back and forth on this. `Suggests` is probably the right thing to do.

**Comment by MilesMcBain** [comment]
Added `tibble (>= 1.2)` to `Suggests`.
