### ISSUE TITLE
X11 support note

### ISSUE THREAD

**Issue by jonocarroll** [MilesMcBain/datapasta#4]
For Linux users, `clipr` will require either `xclip` or `xsel` to be installed, external to `R`. `datapasta` inherits this dependency, so you may wish to make a note of it in the README. `clipr` does throw its own error message noting this, but it can't hurt to mention it up front.

**Comment by MilesMcBain** [comment]
Yep. Which did you go with? I've only tested with `xsel`.

**Comment by jonocarroll** [comment]
> "Clipboard on X11 requires 'xclip' (recommended) or 'xsel'."

`xclip`. Worked fine. Available in Ubuntu `apt` repositories.

**Comment by MilesMcBain** [comment]
Done!
