### ISSUE TITLE
remove dependency on R > 3.3.0 via backports?

### ISSUE THREAD

**Issue by shabbybanks** [MilesMcBain/datapasta#44]
Presumably the dependency on 3.3.0 is for the `strrep` function, which is available from the [`backports` package](https://github.com/mllg/backports). Is there other functionality required?

**Comment by MilesMcBain** [comment]
Thanks for the suggestion. The dependencies are `strrep` and `trimws`. I don't think I'll pursue the `backports` idea for now. 

Although `backports` is a nice way for people who are stuck on an early version of R, for example in an enterprise Standard Operating Environment, to run `datapasta`. If you're out there in this situation, you could download the package archive from CRAN and hack the `DESCRIPTION` to push back the version, making to load `strrep` and `trimws` from `backports`. Alternately you could fork the package on github, make the `DESCRIPTION` changes and build the package yourself.
