### ISSUE TITLE
Guess the presence/absence of header row for tribble_paste()

### ISSUE THREAD

**Issue by MilesMcBain** [MilesMcBain/datapasta#46]
I saw someone using `datapasta` to make quick plots from selected pieces of an excel workbook. It was a little annoying because they were just grabbing bare blocks of data which had the first row converted to a header when they pasted. They had to un-headerise the first row and make a new dummy one.

I reckon we can guess the first row is not a header if `readr` guesses types identically to the rest of the dataframe. Would fail in the special case of ALL character data. But, maybe some analysis of factors can avoid some cases of that too.

**Comment by jonocarroll** [comment]
Is this guessed prior to the columns being analysed? Does the function have an idea about what the column types are at that point?

If it's before that is analysed, how about 

    header = sum(!is.na(suppressWarnings(as.numeric(dat[1, ])))) != length(dat[1, ])

i.e. assume a header row is *not* present if all of the values in the first row are numeric (or equivalent to).

Or just add a `header` argument to the `*_paste()` functions.

**Comment by MilesMcBain** [comment]
It's hard to get this right. I've added an implementation that I think we will be useful sometimes. If the first row has identical types to the rest, I assume it is data, UNLESS the identical is all character. 

There are some edge cases that can mean you still get data parsed as your header. e.g. first row contains an integer while rest of column has decimal places. Oh well.
