### ISSUE TITLE
"invalid 'times' value" error on factor column?

### ISSUE THREAD

**Issue by pgensler** [MilesMcBain/datapasta#62]
It seems like datapasta is attempting to treat factors as Date times in a normal dataframe? 
This is using datapasta 2.0.0

```r
a1 = c("B1","B2","B3","B4","B5")
a2 = c("IT,GE,FB,AI","GE,AI","FB,IT,AI","GE,IT,FB","AI")
a12 = data.frame(a1,a2)
datapasta::tribble_paste(a12)
Error in strrep(" ", char_length - nchar(char_vec)) : 
  invalid 'times' value
```

Traceback:
```r

> traceback()
12: strrep(" ", char_length - nchar(char_vec))
11: paste0(strrep(" ", char_length - nchar(char_vec)), char_vec)
10: pad_to(render_type(char_vec, char_type), char_length)
9: (function (char_vec, char_type, char_length) 
   {
       pad_to(render_type(char_vec, char_type), char_length)
   })(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]])
8: mapply(render_type_pad_to, col, input_table_types, col_widths)
7: paste0(mapply(render_type_pad_to, col, input_table_types, col_widths), 
       ",")
6: paste0(paste0(mapply(render_type_pad_to, col, input_table_types, 
       col_widths), ","), collapse = " ")
5: paste0(strrep(" ", oc$indent_context + oc$nspc), paste0(paste0(mapply(render_type_pad_to, 
       col, input_table_types, col_widths), ","), collapse = " "), 
       "\n", collapse = "")
4: FUN(X[[i]], ...)
3: lapply(X = as.data.frame(t(input_table), stringsAsFactors = FALSE), 
       FUN = function(col) {
           paste0(strrep(" ", oc$indent_context + oc$nspc), paste0(paste0(mapply(render_type_pad_to, 
               col, input_table_types, col_widths), ","), collapse = " "), 
               "\n", collapse = "")
       })
2: tribble_construct(input_table, oc = output_context)
1: datapasta::tribble_paste(a12)
```

**Comment by pgensler** [comment]
For completeness, adding `stringsAsFactors= FALSE` to the data.frame creation works perfectly, but I'd imagine this is related: https://github.com/MilesMcBain/datapasta/issues/58

**Comment by MilesMcBain** [comment]
Yep related to that issue. On `dev`, this should just fall back to pasting as string, as if you had written set `stringsAsFactors` to `False`. Factors have a particular difficulty in that there's no nice way to print each row of a tribble independently that will work as you expect. So even if we tried to do:
```
...
~a1,
as.factor("B1"),
as.factor("B2")
```

etc. This will fail because the factors have different sets of levels. You'd need to convert to factor and set all the levels by looking at the rest of the column. It could be done, but I don't think it would look great. I also do not have a sense that special factor handling is in high demand. Any thoughts?

**Comment by pgensler** [comment]
Yeah, I'm not sure that factors are in high demand, so take the following with a grain of salt. I would think doing something like the following could be a solution:

This might be something to ask the tibble authors about more, as maybe there is a cleaner way to achieve the following?

-Convert column to string
-Call `unqiue$df` for unique vals
-Use those values to create factor column

**Comment by MilesMcBain** [comment]
I've fixed the bug, but I don't think I'll change the factor behaviour at this stage.
