### ISSUE TITLE
Handle quoted csv's that contain comma's in quotes.

### ISSUE THREAD

**Issue by MilesMcBain** [MilesMcBain/datapasta#7]
The primitive parsing strategy does not currently respect things like:

```
name, age
"claus, santa",1746
```

Right now I do not have an easy way to handle it, since the delimiter has to be guessed.

assuming the guessing algorithm can be tweaked to accurately guess "," as the separator, a `switch` could be used to make a call to `read.csv()` instead of `read.table` which would handle the quotes.

**Comment by drchriscole** [comment]
Only just come across this great addin. Will be really useful!

However, I need to add that this is quite an important issue. Many official reports, especially those with budgets involved, quote numbers with the thousands separator (e.g. www.sfc.ac.uk/nmsruntime/saveasdialog.aspx?lID=19286&sID=11697). 

There's a locale issue here also. In most continental European countries the comma is used as the decimal point marker.

Both of the above don't work well without manual intervention.

**Comment by MilesMcBain** [comment]
Thanks @drchriscole, `datapasta` can handle these cases to some degree. `tribble_paste` will correctly parse the numbers in your sheet, and `dp_set_decimal_mark()` can be used to handle alternate representations of decimals.

It seems that `vector_paste()` doesn't handle the commas which is interesting. I'll create a new issue for that.

**Comment by drchriscole** [comment]
You're right `tribble_paste()` does work, however, "Paste as data.frame" doesn't. Somehow the formatting introduces carriage returns within the data e.g. this is the result of a paste from excel (note the line breaks at a few of the thousand's separator):

```
data.frame(stringsAsFactors=FALSE,
           A = c("Aberdeen, University of", "Abertay Dundee, University of",
                 "Dundee, University of", "Edinburgh Napier University",
                 "Edinburgh, University of", "Glasgow Caledonian University",
                 "Glasgow School of Art", "Glasgow, University of",
                 "Heriot-Watt University", "Highlands and Islands, University of the",
                 "Open University in Scotland", "Queen Margaret University, Edinburgh",
                 "Robert Gordon University", "Royal Conservatoire of Scotland", "SRUC",
                 "St Andrews, University of", "Stirling, University of",
                 "Strathclyde, University of", "West of Scotland, University of the"),
           B = c("14,721,000", "592,000", "11,326,000", "1,335,000", "55,278,
                000", "2,328,000", "978,000", "31,397,000", "10,266,000", "1,
                314,000", "-", "569,000", "1,075,000", "254,000", "2,202,000",
                 "14,052,000", "6,439,000", "14,478,000", "1,213,000"),
           C = c("3,696,000", "67,000", "3,368,000", "299,000", "13,181,000",
                 "324,000", "215,000", "7,815,000", "1,976,000", "999,000",
                 "-", "179,000", "159,000", "7,000", "1,208,000", "2,536,000", "709,
                000", "3,765,000", "217,000"),
           D = c("1,565,000", "38,000", "4,508,000", "65,000", "9,165,000",
                 "112,000", "-", "7,996,000", "236,000", "61,000", "-", "47,
                000", "20,000", "-", "-", "871,000", "150,000", "551,000", "66,
                000"),
           E = c("19,982,000", "697,000", "19,202,000", "1,699,000", "77,624,
                000", "2,764,000", "1,193,000", "47,208,000", "12,478,000", "2,
                374,000", "-", "795,000", "1,254,000", "261,000", "3,410,000",
                 "17,459,000", "7,298,000", "18,794,000", "1,496,000"),
           F = c("899,202", "32,175", "717,428", "79,779", "3,342,481", "129,
                483", "58,248", "1,914,509", "597,711", "112,931", "-", "36,
                521", "60,250", "12,743", "166,492", "809,902", "348,998", "890,
                707", "69,819")
)

```

**Comment by MilesMcBain** [comment]
Very good example thanks :)
