### ISSUE TITLE
FR: Add data.table support

### ISSUE THREAD

**Issue by cderv** [MilesMcBain/datapasta#70]
Following a discussion in [rstudio community](https://community.rstudio.com/t/best-practices-how-to-prepare-your-own-data-for-use-in-a-reprex-if-you-can-t-or-don-t-know-how-to-reproduce-a-problem-with-a-built-in-dataset/5346/12), 

a `datatable_paste` and `datatable_construct` could be a great addition to complement `df_paste` / `df_contruct` and `tribble_paste` / `tribble_construct`

**Comment by MilesMcBain** [comment]
Merged.
