### ISSUE TITLE
IDEA: Transform dput output from clipboard to tibble,  dataframe or data.table

### ISSUE THREAD

**Issue by cderv** [MilesMcBain/datapasta#80]
This is based on this question
https://community.rstudio.com/t/convert-dput-output-clipboard-to-a-data-frame-or-tibble-tribble/16050/6

The idea would be to copy a dput output and be able to use `*_paste` family function. 

would it be in the scope of this 📦 ? 
There seems to be other solution currently existing (`read.so` 📦 , `wrapr` 📦 )

**Comment by MilesMcBain** [comment]
I like this. The machinery for this to happen is already kind of there for the 'Fiddle Selection' Addin.

The one issue I see is CRAN being unhappy with a function that evaluates code on the clipboard. It could cause trouble.

**Comment by MilesMcBain** [comment]
Added to `eval_clip*` functions in 04664a1df80ee63e37aedee1faa5e7a11c0d50c1.

I prefer to make it explicit to the user that they are about to evaluate code they just copied. Also attempting to parse all data before pasting could slow things down a little.
