### ISSUE TITLE
Error when pasting from Excel, when there are empty cells in the last column

### ISSUE THREAD

**Issue by vladtarko** [MilesMcBain/datapasta#81]
I noticed that when you're trying to paste data from Excel, sometimes the "Text could not be parsed as table." error appears. This only  happens when the data includes empty cells in the last column. (If there are empty cells in any other columns, it works well, with the empty cells converted to NAs.)

For example copy-pasting this table *from Excel* will give the error:

A | B | C
-- | -- | --
1 | 5 | 9
2 | 6 |  
3 | 7 | 10
4 | 8 | 11

The problem appears to be only from Excel. For instance if you copy-paste the above table from the browser, it works well. In Excel you can prevent the problem if you put a space instead of the empty cell, but obviously, ideally, it should work with the empty cell as well.

**Comment by MilesMcBain** [comment]
This is not great! Thanks for reporting it.

**Comment by noamross** [comment]
This also occurs when copy and pasting from Google Sheets

**Comment by MilesMcBain** [comment]
All fixed.
