### ISSUE TITLE
pasting into a dataframe WITHOUT printing the tibble

### ISSUE THREAD

**Issue by randomgambit** [MilesMcBain/datapasta#82]
Hello there! This is a really nice package. I wonder if there is a way to 

- copy data from excel
- paste directing into a tibble

without showing the tibble in the R script. Indeed, my copypasted data is pretty big and the resulting tibble is very large. I just want to store it in a proper tibble directly

Can `datapasta` do that?
Thanks!

**Comment by MilesMcBain** [comment]
No it can't. Under the hood it uses `clipr` and this may suit your needs, see: https://github.com/mdlincoln/clipr
