### ISSUE TITLE
Vignette Example: Pasting a list as a horizontal vector

### ISSUE THREAD

**Issue by psalveson** [MilesMcBain/datapasta#83]
Hello,

I'm using datapasta 3.0.0 and I found an inconsistency while going through the package vignette. 

The section "Pasting a list as a horizontal vector with vector_paste()" states that the "paste as vector" addin allows going from this:

Mint    Fedora  Debian  Ubuntu  OpenSUSE

to this:

c("Mint", "Fedora", "Debian", "Ubuntu", "OpenSUSE")

But when I select the space delimited text and use the "paste as vector" addin, I get this:

c("Mint    Fedora  Debian  Ubuntu  OpenSUSE")

Which is a vector, but not the one I was expecting. I'm not sure if this is the intended behavior. Text in the example doesn't say that spaces are valid separators, so maybe this is expected behavior and the example I referenced needs to be removed? The other 2 examples (separated by commas and newlines) paste into R as expected.

Peter

**Comment by MilesMcBain** [comment]
Thanks for reporting this. I think my intention was for that to work so I'll investigate. You can also turn that into a vector using the fiddle selection addin.
