### ISSUE TITLE
Support empty tibbles?

### ISSUE THREAD

**Issue by krlmlr** [MilesMcBain/datapasta#91]
For programmatic workflows.

Also, is it expected that `tribble_construct()` returns invisibly? Maybe return a string classed with `"glue"` for nice formatting?

``` r
datapasta::tribble_construct(tibble::tibble(a = character(), b = integer()))
#> Warning in max(vapply(X = df_col, FUN = nchar_type, FUN.VALUE =
#> numeric(1), : no non-missing arguments to max; returning -Inf

#> Warning in max(vapply(X = df_col, FUN = nchar_type, FUN.VALUE =
#> numeric(1), : no non-missing arguments to max; returning -Inf
datapasta::tribble_construct(tibble::tibble(a = "a", b = 1L))
cat(datapasta::tribble_construct(tibble::tibble(a = "a", b = 1L)))
#> tibble::tribble(
#>    ~a, ~b,
#>   "a", 1L
#>   )
```

<sup>Created on 2019-03-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by MilesMcBain** [comment]
Yeah an empty tibble should be supported :+1:

Returning invisibly is a historical hangover that could be removed :+1:

**Comment by MilesMcBain** [comment]
@krlmlr, had a go at implementing this. Interstingly I found `tibble::tribble` doesn't support declaration of zero length rows:

``` r

tibble::tribble(
          ~a,           ~b,
          character(0), character(0)  )
#> # A tibble: 1 x 2
#>   a         b        
#>   <list>    <list>   
#> 1 <chr [0]> <chr [0]>
```

<sup>Created on 2019-08-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MilesMcBain** [comment]
Well, this works, but I can't match the types of the columns passed in. It produces cols of type logical:

```
tibble::tribble(
          ~a,           ~b)

```

**Comment by MilesMcBain** [comment]
Implemented a `tibble` fallback
