### ISSUE TITLE
Review paste clipboard evaluation

### ISSUE THREAD

**Issue by MilesMcBain** [MilesMcBain/datapasta#96]
These new functions might cause headaches with CRAN. I am unsure about whether they belong in datapasta or in some other package.

**Comment by MilesMcBain** [comment]
Hey @jonocarroll I think it was you who suggested these. Do you use either `eval_clip_dpasta`, `eval_clip_tribble`? I'm thinking I'm going to remove them as I feel like they're probably not widely used and could expose me to hassles with CRAN.

**Comment by jonocarroll** [comment]
I'm not sure this was me; I don't recognise those. Do as you feel is necessary.

**Comment by MilesMcBain** [comment]
Removed them!
